### ISSUE TITLE
README no longer up-to-date (KeyError)

### ISSUE THREAD

**Issue by boyuan12** [cloudconvert/cloudconvert-python#14]
Hi,

So when I try to use the sample code in README: 
```python
file = res.get("result").get("files")[0]
res = cloudconvert.download(filename=file['filename'], url=file['url'])
```

I got this error: `KeyError: 'url'`.

I tried to print out the URL object, and I got: `{'filename': 'demo-flask.zip', 'size': 679}`, which doesn't include URL key.

**Comment by josiasmontag** [comment]
`url` is only available for `export/url` tasks. Please make sure this is an `export/url` task.

**Comment by boyuan12** [comment]
Thanks, now it works.
