### ISSUE TITLE
Python Wrapper - Api Module

### ISSUE THREAD

**Issue by rejuashes** [cloudconvert/cloudconvert-python#2]
Hi , 

When running the code snippets generated from the console-api to convert pdf to docx getting the below mentioned error.

AttributeError: 'module' object has no attribute 'Api'.

i have installed using
pip install cloudconvert

regards,

rajith

**Comment by josiasmontag** [comment]
Please share your complete code. Thanks.

**Comment by rejuashes** [comment]
Please find below the code, which is taken from the console api code snippets.

Should i have a paid version api key for the same to work?

import cloudconvert
api = cloudconvert.Api('myapikey')
     
process = api.convert({
    "inputformat": "pdf",
    "outputformat": "docx",
    "input": "upload",
    "file": open('inputfile.pdf', 'rb')
})
process.wait()
process.download()

**Comment by josiasmontag** [comment]
Paid version is not required for using the API.
Is it possible that your file is named ``cloudconvert.py``? If yes, rename it to something else. (and delete the .pyc file)

**Comment by rejuashes** [comment]
Bingo, that was it.

Thanks a lot.

**Comment by linky00** [comment]
Love coming back to find someone had the EXACT SAME strange specific issue 2 years ago.

**Comment by Tusquito** [comment]
Yo i have the exact same problem a lot of time ago, does someone has a fix ? Ty
`import cloudconvert

api = cloudconvert.Api('api_key')
 
process = api.convert({
    'inputformat': 'ods',
    'outputformat': 'xlsx',
    'input': 'upload',
    'file': 'test.ods'
})
process.wait() 
process.download() `

**Comment by nathanturczan** [comment]
Which .pyc file should I delete? I'm getting this error and my file is not named cloudconvert.py, it's called transcode.py. Here's my code:

`import cloudconvert
api = cloudconvert.Api('MyApiKey')
 
process = api.convert({
    "inputformat": "mov",
    "outputformat": "mkv",
    "input": "upload",
    "filename": "out.mkv",
    "file": open('TestVideo.mov', 'rb')
})
process.wait()
process.download()`

**Comment by CrickCrock28** [comment]
I have the same code and the same problem but the file is not named "cloudconvert.py". What I have to do?
