### ISSUE TITLE
Python SDK Job.create() doesn't propagate the request status code

### ISSUE THREAD

**Issue by BeGeos** [cloudconvert/cloudconvert-python#22]
Using the Python SDK and following the instructions the Job.create() return a dict. It would be super useful if it could also carry the status code of the request. In the docs it says that: `Jobs and tasks that completed with an error, do have status set to error`
It would be nice to have it in the SDK as well. Or maybe there is already, in that case awesome, and you should really include it in the README

Thanks,

Marco

**Comment by josiasmontag** [comment]
You can get the job status via `job.status` from the return object. If the API responds with a non 2xx response code the SDK will throw an exception.

**Comment by BeGeos** [comment]
That's right. This is what I am saying, because at the moment there is no way from the exception to get the status code of the request

**Comment by josiasmontag** [comment]
The thrown exception depends on the status code, for example HTTP 403 will throw `ForbiddenAccess`, HTTP 422 throws `ResourceInvalid` etc.
