### ISSUE TITLE
How to convert from pdf to docx in local storage

### ISSUE THREAD

**Issue by yugaljain03** [cloudconvert/cloudconvert-python#23]
Hi @josiasmontag , Can you tell me what job I need to create if I want to convert `test.pdf` into `test.docx`?
I am not getting what should I do first either import or direct convert because input pdf file is not present on any url, it is primarily located in my local storage and I want to store converted file also in my local storage..

Please help me in this as it's very important for me..
Thanks

**Comment by josiasmontag** [comment]
There are code examples in the README how to upload input files and how to download output files.

Please note that this is an issue trucker and not a support forum.
