### ISSUE TITLE
How to set document parameters

### ISSUE THREAD

**Issue by reimax** [cloudconvert/cloudconvert-python#28]
I'm passing raw html markup and want to get a document in docx format. This I have already done. Question: is it possible to set document parameters? I need to set page margins and automatic numbering.

**Comment by josiasmontag** [comment]
No, such options are not supported for HTML -> DOCX.

This is not an issue of the Python SDK but a question about the CloudConvert API directly. For such support requests please use the contact form at https://cloudconvert.com/contact.
