### ISSUE TITLE
Error: Saving to S3 failed

### ISSUE THREAD

**Issue by mazulo** [cloudconvert/cloudconvert-python#3]
I'm using `cloudconvert==1.0.0` and trying to send to S3 the converted file with the following code (accordingly to the [docs](https://cloudconvert.com/api/s3))

```python
process.start({
    'input': 'upload',
    'file': open('music_test.mp3', 'rb'),
    "outputformat": "m4a",
    "output": {
        "s3": {
            "accesskeyid": "my-access-key",
            "secretaccesskey": "secret-key",
            "bucket": "bucket.name"
        }
    }
})
```

But I'm always getting this error message even already setting up permission to everyone list/upload/delete files in this bucket:

```bash
cloudconvert.exceptions.BadRequest: Saving to S3 failed: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Code: InvalidRequest)
```

Looks like I have to do some authentication process before this, but I didn't see anything from docs.

**Comment by mazulo** [comment]
I figure out what was happening:

I created a S3 bucket using Ohio as region (us-east-2) and after some researches I figure out that this region doesn't support anymore the Signature Version 2 ("V2"), only V4 ([reference](http://stackoverflow.com/a/26538266)). I created another S3 bucket by now setting up as region US Standard (that support V2, full list [here](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region)).

After that everything works very well 😃

**Comment by josiasmontag** [comment]
Just for the reference: v4 signatures are already supported. To make it work, you need to specify the region in your request. In your case:
```python
process.start({
    'input': 'upload',
    'file': open('music_test.mp3', 'rb'),
    "outputformat": "m4a",
    "output": {
        "s3": {
            "accesskeyid": "my-access-key",
            "secretaccesskey": "secret-key",
            "bucket": "bucket.name",
            "region": "us-east-2"
        }
    }
})
```

**Comment by mazulo** [comment]
Nice! @josiasmontag thanks for the tip 😃
