### ISSUE TITLE
Allow download to variable instead of file

### ISSUE THREAD

**Issue by imraanparker** [cloudconvert/cloudconvert-python#9]
Can the API allow downloading the content into a variable instead of to file? Currently, I have to download the document and then read it back in.

Perhaps something like this :-

`content = process.download(inline=True) OR content = process.downloadAsRaw()`

**Comment by josiasmontag** [comment]
This issue is related to the API v1 SDK which has been replaced by the API v2 SDK in meantime. If you have this issue with the new SDK as well, feel free to open a new issue.
